spring:
  http:
    multipart:
      max-file-size: 300KB
      max-request-size: 300KB
  datasource:
    url: jdbc:mysql://localhost:3306/sstrash
    username: root
    password: 0913
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp

  jpa:
    hibernate:
      ddl-auto: update


mybatis:
  mapper-locations: mapper/*xml



#application:
#  graph: ./graph/YOLO/yolo-voc.pb
#  label: ./graph/YOLO/yolo-voc-labels.txt
#  outputDir: ./predicted
#  uploadDir: ./upload-dir
#  imageSize: 416
#  imageMean: 255